ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim

RUN apt update && apt install -y build-essential
RUN pip install -U pip && pip install poetry==1.5.1
RUN mkdir /app
RUN python -m venv "/venv"
ENV VIRTUAL_ENV "/venv"

WORKDIR /app
