name: Docker

on:
  push:

env:
  IMAGE_NAME: pybase

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name == 'push'
    strategy:
        matrix:
          ver:
            - v1
            - v2
          image:
            - compile
            - runtime
          python:
            - '3.11.13'
            - '3.12.11'
            - '3.13.5'
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build ${{ matrix.ver }} --build-arg PYTHON_VERSION=${{ matrix.python }} --file ${{ matrix.ver }}/Dockerfile.${{ matrix.image }} --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION="${{ matrix.python }}-${{ matrix.image }}-${{ matrix.ver }}"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
