name: Docker

on:
  push:

env:
  IMAGE_NAME: pybase

jobs:
  push:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event_name == 'push'
    strategy:
        matrix:
          image:
            - compile
            - runtime
          python:
            - '3.7.17'
            - '3.8.18'
            - '3.9.18'
            - '3.10.13'
            - '3.11.6'
            - '3.12.0'
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --build-arg PYTHON_VERSION=${{ matrix.python }} --file Dockerfile.${{ matrix.image }} --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION="${{ matrix.image }}-${{ matrix.python }}"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
